:projectKey: TimefoldAI_timefold-solver-enterprise
// TODO Enable Sonar
// :sonarBadge: image:https://sonarcloud.io/api/project_badges/measure?project={projectKey}
// :sonarLink: link="https://sonarcloud.io/dashboard?id={projectKey}"

:branch: main

_Planning optimization made easy._ +
https://timefold.ai[timefold.ai]

image:https://img.shields.io/badge/Java-17+-brightgreen.svg?style=for-the-badge["JVM support", link="https://sdkman.io"]

image:https://img.shields.io/badge/stackoverflow-ask_question-orange.svg?logo=stackoverflow&style=for-the-badge["Stackoverflow", link="https://stackoverflow.com/questions/tagged/timefold"]
image:https://img.shields.io/github/discussions/TimefoldAI/timefold-solver?style=for-the-badge&logo=github["GitHub Discussions", link="https://github.com/TimefoldAI/timefold-solver/discussions"]
image:https://img.shields.io/github/issues/TimefoldAI/timefold-solver-enterprise?style=for-the-badge&logo=github["GitHub Issues", link="https://github.com/TimefoldAI/timefold-solver-enterprise/issues"]

== Timefold Solver Enterprise Edition

_Timefold Solver Enterprise Edition_ is a commercial offering by _Timefold_.
It enhances the _Timefold Solver Community Edition_ by features such as nearby selection and multi-threaded solving.
Even though the source code is available here, *_Timefold Solver Enterprise Edition_ is not open source*.

You are not allowed to modify, distribute, or use this source code and resulting binaries
for any purpose other than for development and testing.
*To use _Timefold Solver Enterprise Edition_ in production, you need a license.*
https://timefold.ai/pricing/[See Timefold pricing information.]

Users who do not require the additional features are encouraged to use the https://github.com/TimefoldAI/timefold-solver/[_Timefold Solver Community Edition_] instead.
The Community Edition is a free and open source project, licensed under the Apache License 2.0.

== Using Timefold Solver Enterprise Edition

To use Timefold Solver Enterprise Edition, first https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens[create a GitHub access token] with the `read:packages` permission.

NOTE: In the near future, we will introduce anonymous access to _Timefold Solver Enterprise Edition_ packages. This step will no longer be required.

=== Step 1a: Using Timefold Solver Enterprise Edition in Maven

. Configure Maven to use the GitHub access token
+
Edit the existing or create a new `settings.xml` in `~/.m2` to add server authentication:
+
[source, xml]
----
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>timefold-solver-enterprise</id>
      <username>GitHub user name</username>
      <password>GitHub token</password>
    </server>
  </servers>
</settings>
----

. Configure your Maven project to use the Enterprise Edition Maven repository:

    <project>
      ...
      <repositories>
        <repository>
          <id>timefold-solver-enterprise</id>
          <name>Timefold Solver Enterprise</name>
          <url>https://maven.pkg.github.com/TimefoldAI/timefold-solver-enterprise</url>
        </repository>
      </repositories>
      ...
    </project>
+
Note that the repository `ID` is the same as the server `ID` from the previous step.

=== Step 1b: Using Timefold Solver Enterprise Edition with Gradle

Configure your Gradle project to use the Enterprise Edition Maven repository:

    repositories {
      mavenCentral()
      maven {
        url "https://maven.pkg.github.com/TimefoldAI/timefold-solver-enterprise"
        credentials {
            username = "GitHub user name"
            password = "GitHub token"
        }
        authentication {
            basic(BasicAuthentication)
        }
      }
    }
=== Step 2: Replace Community Edition artifacts
Having done that, replace the following artifacts provided by the Community Edition with their Enterprise Edition counterparts:

|===
|Community Edition|Enterprise Edition

|`ai.timefold.solver:timefold-solver-bom`
|`ai.timefold.solver.enterprise:timefold-solver-enterprise-bom`

|`ai.timefold.solver:timefold-solver-core`
|`ai.timefold.solver.enterprise:timefold-solver-enterprise-core`

|`ai.timefold.solver:timefold-solver-quarkus`
|`ai.timefold.solver.enterprise:timefold-solver-enterprise-quarkus`

|`ai.timefold.solver:timefold-solver-spring-boot-starter`
|`ai.timefold.solver.enterprise:timefold-solver-enterprise-spring-boot-starter`
|===

If your project only uses a subset of the Community Edition artifacts listed above,
only replace those with their Enterprise Edition counterparts.
There is no need to add the other artifacts listed.