:projectKey: TimefoldAI_timefold-solver-enterprise
// TODO Enable Sonar
// :sonarBadge: image:https://sonarcloud.io/api/project_badges/measure?project={projectKey}
// :sonarLink: link="https://sonarcloud.io/dashboard?id={projectKey}"

:branch: main

_Planning optimization made easy._ +
https://timefold.ai[timefold.ai]

image:https://img.shields.io/badge/Java-17+-brightgreen.svg?style=for-the-badge["JVM support", link="https://sdkman.io"]

image:https://img.shields.io/badge/stackoverflow-ask_question-orange.svg?logo=stackoverflow&style=for-the-badge["Stackoverflow", link="https://stackoverflow.com/questions/tagged/timefold"]
image:https://img.shields.io/github/discussions/TimefoldAI/timefold-solver?style=for-the-badge&logo=github["GitHub Discussions", link="https://github.com/TimefoldAI/timefold-solver/discussions"]
image:https://img.shields.io/github/issues/TimefoldAI/timefold-solver-enterprise?style=for-the-badge&logo=github["GitHub Issues", link="https://github.com/TimefoldAI/timefold-solver-enterprise/issues"]

== Timefold Solver Enterprise Edition

_Timefold Solver Enterprise Edition_ is a commercial offering by _Timefold_.
It enhances the https://github.com/TimefoldAI/timefold-solver[Timefold Solver Community Edition] by features such as nearby selection and multi-threaded solving.
Even though the source code is available here, *_Timefold Solver Enterprise Edition_ is not open source*.

You are not allowed to modify, distribute, or use this source code and resulting binaries
for any purpose other than for development and testing.
*To use _Timefold Solver Enterprise Edition_ in production, https://timefold.ai/company/contact/[contact Timefold] to obtain a license.*


Users who do not require the additional features are encouraged to use the https://github.com/TimefoldAI/timefold-solver/[_Timefold Solver Community Edition_] instead.
The Community Edition is a free and open source project, licensed under the Apache License 2.0.

Visit our https://timefold.ai/pricing[pricing page] to compare Timefold Solver Community Edition vs Timefold Solver Enterprise Edition.

== Switch to Enterprise Edition

In order to switch from Timefold Solver Community Edition to Enterprise Edition,
first reference the Enterprise Edition Maven repository in your project.
If you use Maven, add the following repository to your `pom.xml`:

[source,xml,options="nowrap"]
----
<project>
  ...
  <repositories>
    <repository>
      <id>timefold-solver-enterprise</id>
      <name>Timefold Solver Enterprise</name>
      <url>https://timefold.jfrog.io/artifactory/releases/</url>
    </repository>
  </repositories>
  ...
</project>
----

If you use Gradle, add the following in your `build.gradle`:

[source,groovy,options="nowrap"]
----
repositories {
  mavenCentral()
  maven {
    url "https://timefold.jfrog.io/artifactory/releases/"
  }
}
----

Having done that, replace the following artifacts provided by the Community Edition with their Enterprise Edition counterparts:

|===
|Community Edition|Enterprise Edition

|`ai.timefold.solver:timefold-solver-bom`
|`ai.timefold.solver.enterprise:timefold-solver-enterprise-bom`

|`ai.timefold.solver:timefold-solver-core`
|`ai.timefold.solver.enterprise:timefold-solver-enterprise-core`

|`ai.timefold.solver:timefold-solver-quarkus`
|`ai.timefold.solver.enterprise:timefold-solver-enterprise-quarkus`

|`ai.timefold.solver:timefold-solver-spring-boot-starter`
|`ai.timefold.solver.enterprise:timefold-solver-enterprise-spring-boot-starter`
|===

If your project only uses a subset of the Community Edition artifacts listed above,
only replace those with their Enterprise Edition counterparts.
There is no need to add the other artifacts listed.
